config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :posts do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name,:birth,:telephone])
  end


  private
  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def index
    @posts = Post.all
  end


  def search
    @posts = Post.where("title like ?","%#{params[:search]}%")
    render "posts/index"
  end

  def show
    @post.viewer = (@post.viewer) +1
    @post.save
  end


  def new
    @post = Post.new
  end

  def edit
  end


  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end


  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
require 'redcarpet/compat'
module ApplicationHelper
  def markdown(content)
    render = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html:true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript:true
    }

    mark = Redcarpet::Markdown.new(render, options)

    mark.render(content).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoderschoolPrework</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>


<nav class="navbar navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="<%= new_user_session_path %>">
      Prework Ruby on Rails
    </a>
    <ul class="nav navbar-nav pull-xs-right">
      <li class="nav-item active">
        <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>

        <% else %>
            <a class="nav-link" href="<%= new_user_session_path %>">Log in</a></li>
        <% end %>
        </ul>
    <%= form_tag search_posts_path, method: :get, class: "form-inline" do %>
        <%= text_field_tag 'search', nil, class: "form-control" %>
        <%= submit_tag "Search",class: "btn btn-outline-info" %>
    <% end %>
  </div>
  <!-- </div>-->
</nav>


<div class="container" style="margin-top: 20px">
  <div class="row row-offcanvas row-offcanvas-left">

    <!-- sidebar -->
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
      <h2 style="text-transform: uppercase;color: #33acb7; text-align: left; width: 95%;">Coderschool</h2>
      <ul class="nav">

        <li><a href="<%= posts_path %>">Post</a></li>
        <li><a href="/about me.html">About</a></li>

      </ul>
    </div>

    <!-- main area -->
    <div class="col-xs-12 col-sm-9">

      <%= yield %>
    </div><!-- /.col-xs-12 main -->
  </div><!--/.row-->
</div><!--/.container-->


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
    <% if post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="form-group">
      <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
      </br>
      </br>

      <%= f.label :content, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :content, class: "form-control", style: " height: 50vh;" %>
      </div>
    </div>


      <%= f.submit class: "btn btn-primary"%>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
    <div class="list-group" style="margin-top: 20px">
      <a class="list-group-item list-group-item-action list-group-item-info" href="<%= post_path post.id %>">
        <h3><%= post.title %></h3>
        <p class="list-group-item-text">
          <%= "#{post.user.name} posted at #{post.created_at} Viewer: #{post.viewer}" %>
          <% if current_user == post.user %>
              <%= link_to "Delete", post, method: :delete, class: "btn-danger", style: "float:right", data: {
                  confirm: "Are you sure?"}
               %>
          <% end %>
        </p>

      </a>
    </div>
<% end %>
</br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-xs-12 col-sm-9" style="padding-left: 0px">
  <div class="form-group">
    <p style="padding: 6px 0px">
      <strong style="align-content: center">Title:</strong>
      <%= @post.title %>
    <p>
      <strong>Content:</strong>
      <%= markdown @post.content %>
    </p>
    <%= link_to 'Back', posts_path %>
  </div>
</div>
</p>

<div class="col-xs-12 col-sm-3">
  <% if current_user == @post.user %>
      <a class="btn btn-primary" href="<%= edit_post_path %>"> Edit</a>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>